#ifndef MICROPY_INCLUDED_MPCONFIGBOARD_H
#define MICROPY_INCLUDED_MPCONFIGBOARD_H

#define MICROPY_HW_BOARD_NAME       "HW-PUPPET"
#define MICROPY_HW_MCU_NAME         "ESP32-S3"

#define MICROPY_HW_ENABLE_USBDEV    (1)
#define MICROPY_HW_USB_CDC          (1)
#define MICROPY_HW_USB_CDC_NUM      (2)
#define MICROPY_HW_USB_VID          (0x303A)
#define MICROPY_HW_USB_PID          (0x4002)
#define MICROPY_HW_USB_MANUFACTURER_STRING "HW-Puppet"
#define MICROPY_HW_USB_PRODUCT_FS_STRING   "HW-PUPPET"
#define MICROPY_HW_USB_CDC_INTERFACE_STRING "HW-PUPPET REPL"
#define MICROPY_HW_USB_CDC_1_INTERFACE_STRING "HW-PUPPET UART Bridge"

#define MICROPY_HW_CDC0_INTERFACE_NUM (0)
#define MICROPY_HW_CDC1_INTERFACE_NUM (1)

#define MICROPY_HW_UART1_TX         (43)
#define MICROPY_HW_UART1_RX         (44)
#define MICROPY_HW_UART1_BAUDRATE   (115200)
#define MICROPY_HW_UART1_RXBUF      (16384)

#define MICROPY_HW_ENABLE_UART_REPL (0)

#define MICROPY_PSRAM_ENABLE        (1)

// Disable I2C target (slave) mode which requires ESP-IDF v5.5 API
#define MICROPY_PY_MACHINE_I2C_TARGET (0)

#define MODULE_UART_BRIDGE_ENABLED    (1)

void HW_PUPPET_board_startup(void);
#define MICROPY_BOARD_STARTUP         HW_PUPPET_board_startup

#endif